spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - AuthFilter

        - id: beer-product-service
          uri: lb://beer-product-service
          predicates:
            - Path=/api/beer/**
          filters:
            - AuthFilter

        - id: beers-tried-service
          uri: lb://beers-tried-service
          predicates:
            - Path=/api/tried-beer/**
          filters:
            - AuthFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
client:
  SECRET_KEY: "nUnySPRDeX3bt54xAXFMTYc5SXDnGguzKEkof5qMhE252WJn6M9fBJXbBqkehqWeqhuFuFx99y4xrSCBgJ6J38MowTh3ekpXJMUj3T97qhGAkmyoG9whxeqhap5yroxAEhL6uW6UqSYwosaJ42jBCmaGGfE6oYAoGPwhBjEyaPpCBT9ZTwJWPWpyeh9F3D7h3JxoHCZEn3k3rWDu3p3XunEgqGcbzREuUSuRNgxbaZHdQCTDRsUNcRADUpYUR4Bh"
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
server:
  port: 0